name: 'Cache contract bindings'
description: 'Cache contract bindings'
inputs:
  execution-folder:
    description: 'Folder to execute the npm actions'
    required: true
runs:
  using: "composite"
  steps:
    - name: "Compute file hash"
      id: compute-hash
      shell: bash
      working-directory: ${{ inputs.execution-folder }}
      run: |
        OUTPUT=$(sed -n '/abiExporter:/,/}/p' ./hardhat.config.ts | \
        sed -n '/only:/,/]/p' | \
        sed 's/only://' | \
        sed 's/[][,"]//g' | \
        xargs -n 1 -I {} echo "'**/"{}".sol'" | \
        tr '\n' ',')
        echo "::set-output name=hash::$OUTPUT\n"
    - uses: actions/cache@v3
      name: "Cache contract bindings"
      id: smart-contract-cache
      with:
        path: ./bridge/bindings
        key: ${{ runner.os }}-go-${{ hashFiles(steps.compute-hash.hash) }}
    - if: steps.smart-contract-cache.outputs.cache-hit != 'true'
      shell: bash
      working-directory: ${{ inputs.execution-folder }}
      run: npm run build
