name: 'Run the solidity unit tests in groups'
description: 'Run the solidity unit tests in groups'
inputs:
  test-group:
    description: 'Regex to math the folder inside the test folder'
    required: true
  sub-filter-include:
    description: 'Sub folder to include in the search'
    required: true
  sub-filter-exclude:
    description: 'Sub folder to exclude in the search'
    required: true
runs:
  using: "composite"

  steps:
  - shell: bash
    working-directory: ./bridge
    run: npm run clean && npm run compile
  - shell: bash
    working-directory: ./bridge
    run: ls ./test | grep "^${{ inputs.test-group }}" | xargs -n 1 -I {} echo ./test/{}/${{ inputs.sub-filter-include }} | xargs -n 1 -I {} find -P {} -type f -iname '*.ts' -not -path "*/${{ inputs.sub-filter-exclude }}/*" | xargs npm run test-parallel --
