name: 'Run the solidity unit tests in groups'
description: 'Run the solidity unit tests in groups'
inputs:
  test-group:  # id of input
    description: 'Range of the starting letter of the folder contains the tests that will be run'
    required: true
runs:
  using: "composite"

  steps:
  - shell: bash
    working-directory: ./bridge
    run: npm run clean && npm run compile
  # - shell: bash
  #   working-directory: ./bridge
  #   run: find -P ./test/aToken ./test/bToken ./test/chai-setup.ts ./test/contract-mocks' -type f -iname '*.ts
  - shell: bash
    working-directory: ./bridge
    run: ls ./test -d */ | grep "^[${{ inputs.test-group }}]" | xargs -n 1 -I {} echo ./test/{} | tr -s '\n' ' ' | xargs -n 1 -I {} find -path {} -type f -iname '*.ts'