name: Alicenet CI

on:
  push:
    branches: [ main, candidate ]
  pull_request:
    branches: [ main, candidate ]

env:
  NODE_VERSION: 16.x

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bridge
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/node-cache


  solidity-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - test-group: "[a-d]"
          - test-group: "[e]"
            sub-filter-exclude: "ethdkg/phases"
          - test-group: "ethdkg"
            sub-filter-include: "phases"
            matrix.sub-filter-exclude: "accusations"
          - test-group: "ethdkg"
            sub-filter-include: "phases/accusations"
          - test-group: "[f-p]"
          - test-group: "[r-s]"
          - test-group: "[t-z]"

    needs: build
    defaults:
      run:
        working-directory: ./bridge
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-cache
      - uses: ./.github/actions/solidity-tests
        with:
          test-group: ${{ matrix.test-group }}
          sub-filter-include: ${{ matrix.sub-filter-include }}
          sub-filter-exclude: ${{ matrix.sub-filter-exclude }}

  solidity-linter:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./bridge
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-cache
      - run: npm run lint-solidity

  typescript-linter:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./bridge
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-cache
      - run: npm run clean && npm run compile && npm run typechain
      - run: npm run lint
