name: Alicenet CI

on:
  push:
    branches: [ main, candidate ]
  pull_request:
    branches: [ main, candidate ]

env:
  NODE_VERSION: 16.x

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bridge
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/node-cache


  solidity-unit-tests-1:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./bridge
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/solidity-tests
        #running tests from the folders starting with A to D
        with:
          test-group: "a-d"

