name: Alicenet CI

on:
  push:
    branches: [ main, candidate ]
  pull_request:
    branches: [ main, candidate ]

env:
  NODE_VERSION: 16.x

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bridge
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Cache
      uses: actions/cache@v3.0.2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
    - if: steps.node-cache.outputs.cache-hit != 'true'
      run: npm ci


  unit-test:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./bridge
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Download Cache
        id: node-cache
        uses: actions/cache@v3.0.2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm run test-parallel
