name: Alicenet CI

on:
  push:
    branches: [ main, candidate ]
  pull_request:
    branches: [ main, candidate ]

env:
  NODE_VERSION: 16.x

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bridge
    steps:
    - uses: actions/checkout@v3
    - uses: ../.github/actions/node-cache


  solidity-unit-tests:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./bridge
    steps:
      - uses: actions/checkout@v3
      - uses: ../.github/actions/node-cache
      - run: npm run clean && npm run compile
      # - run: npm run test-parallel

